### PR TITLE
Migration to Microsoft.App@2022-01-01-preview Resource Provider

### PR DESCRIPTION
**Pull request by briandenicola**
This Pull Request is to complete the migration to the new ContainerApp Resource Provider started in PR#17. This is required for all ContainerApp applications as laid out here - https://github.com/microsoft/azure-container-apps/issues/109

* The previous pull request had issues because it could not be end-to-end tested. This PR has been tested in my Azure subscription and provisions fully in US East2.  
* Dapr Components are defined in modules/dapr-components and scoped to just the required ContainerApps.
* kubeEnvironment has been migrated to managedEnvironments
* Each ContainerApp had been updated to the new namespace and updated dapr configuration. 
* The deploy.sh script has been updated to include the required extensions to the az cli and registers the Microsoft.App namespace.  
* The Readme.md has been updated with the required manual steps if the deploy.sh script is not used.

### CODE REVIEW

**Comment by alicejgibbons** [comment]
Hey @briandenicola, thanks for your PR! We just finished testing and pushed #17 and it looks like there are some conflicts now with your branch. Mind resolving so I can view a diff of your changes better?

**Comment by alicejgibbons** [comment]
Hey @briandenicola, thanks for your PR! We just finished testing and pushed #17 and it looks like there are some conflicts now with your branch. Mind resolving so I can view a diff of your changes better?

**Comment by alicejgibbons** [comment]
Also curious what you mean by this point as I tested out the PR today e2e and it was working :)
- The previous pull request had issues because it could not be end-to-end tested. This PR has been tested in my Azure subscription and provisions fully in US East2.

**Comment by briandenicola** [comment]
This pull request can be close. The merge conflict are basically redundant at this point. 

> Also curious what you mean by this point as I tested out the PR today e2e and it was working :)
> 
> * The previous pull request had issues because it could not be end-to-end tested. This PR has been tested in my Azure subscription and provisions fully in US East2.

I was referencing the first couple bullets in the initial pull request that the author made when they made the pull around not being able to test daprComponents. It's all good and I'm happy to see their updates merged in.

**Pull request closed without merging**
